print ten_x_plus1(7)
print substitution_cipher("abc Iz this Secure?",6)
print diff_doubles([2,5,1.5,100,3,8,7])
print future_tense(['program','debug','execute','crash','repeat'])
print past_tense(['program','debug','execute','crash','repeat','try'])
print combinations([0,1,2],2)
print combinations(range(5),3)
print combinations(['red','green','blue','black'],2)
print combinations(range(10),6)
